### ISSUE TITLE
lack of docs for usage with official wiremock docker image

### ISSUE THREAD

**Issue by typekpb** [wiremock/wiremock-jwt-extension#3]
### Proposal

The `Readme.md` file should document proper usage in docker.

### Reproduction steps

Having `Dockerfile` with contents:
```
FROM wiremock/wiremock:3.5.2

COPY ./extensions /var/wiremock/extensions
```
where `./extensions` dir contains: `wiremock-jwt-extension-0.1.0.jar` (downloaded from: https://mvnrepository.com/artifact/org.wiremock.extensions/wiremock-jwt-extension/0.1.0)

Running the command results in error:
```
podman build -t foo:latest . && podman run --rm -p 8082:8080 foo:latest --verbose --extensions org.wiremock.extension.jwt.JwtExtensionFactory

STEP 1/3: FROM wiremock/wiremock:3.5.2
STEP 2/3: COPY ./wiremock /home/wiremock
--> dd63ab497386
STEP 3/3: COPY ./extensions /var/wiremock/extensions
COMMIT foo:latest
--> 92a50e4f087e
Successfully tagged localhost/foo:latest
92a50e4f087ec3e2677c0a4a15d91df5faf47c717f64a58f5cb0083a71058b40
2024-05-26 22:06:50.343 Verbose logging enabled
Exception in thread "main" java.lang.ClassCastException: class org.wiremock.extension.jwt.JwtExtensionFactory cannot be cast to class com.github.tomakehurst.wiremock.extension.Extension (org.wiremock.extension.jwt.JwtExtensionFactory and com.github.tomakehurst.wiremock.extension.Extension are in unnamed module of loader 'app')
        at com.github.tomakehurst.wiremock.extension.Extensions.load(Extensions.java:230)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(Unknown Source)
        at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
        at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.base/java.util.stream.ReferencePipeline.forEach(Unknown Source)
        at com.github.tomakehurst.wiremock.extension.Extensions.load(Extensions.java:80)
        at com.github.tomakehurst.wiremock.core.WireMockApp.<init>(WireMockApp.java:107)
        at com.github.tomakehurst.wiremock.WireMockServer.<init>(WireMockServer.java:74)
        at com.github.tomakehurst.wiremock.standalone.WireMockServerRunner.run(WireMockServerRunner.java:71)
        at wiremock.Run.main(Run.java:23)
```

**Comment by typekpb** [comment]
OK, I seem to have found the working way in the meantime, usage of: https://mvnrepository.com/artifact/org.wiremock.extensions/wiremock-jwt-extension-standalone/0.1.0 with command:
```
podman build -t foo:latest . && podman run --rm -p 8082:8080 foo:latest --verbose
```
starts properly, listing the expected extensions:
```
extensions:                   jwt-signing-key-settings-listener,jwt-initialiser,jwt-template-helpers,response-template,webhook
```

Anyway, might be worth documenting in the Readme.md

**Comment by jrnorth** [comment]
+1
This is still an issue with wiremock 3.10.0 and extension version 0.2.0

**Comment by johndevs** [comment]
Ran into this as well, anybody solved this?

**Comment by jrnorth** [comment]
@johndevs I was able to get this to work by copying the [standalone JAR](https://mvnrepository.com/artifact/org.wiremock.extensions/wiremock-jwt-extension-standalone) into the `/var/wiremock/extensions` directory. Here's how I achieved that using Testcontainers:

```java
  @Container
  static final GenericContainer<?> wiremock =
      new GenericContainer<>(DockerImageName.parse("wiremock/wiremock").withTag("3.10.0"))
          .withEnv("WIREMOCK_OPTIONS", "--verbose")
          .withNetwork(network)
          .withNetworkAliases("wiremock")
          .withExposedPorts(8080)
          // copy the standalone extension JAR into the extensions directory
          .withCopyFileToContainer(
              forClasspathResource("wiremock-jwt-extension-standalone.jar"),
              "/var/wiremock/extensions/wiremock-jwt-extension-standalone.jar")
          .withCopyFileToContainer(forClasspathResource("mappings"), "/home/wiremock/mappings")
          .waitingFor(forListeningPorts(8080))
          .withLogConsumer(new Slf4jLogConsumer(WIREMOCK_LOGGER));
```

**Comment by vzhgit** [comment]
Hello!

> Ran into this as well, anybody solved this?

Yep! Our corporate AI was able to solve this problem by comparing this extension with [wiremock-gui](https://github.com/testsmith-io/wiremock-gui) extension and analyzing [wiremock](https://github.com/wiremock/wiremock) project:
```
The JWT extension already has a proper META-INF/services/... file that registers JwtExtensionFactory as an ExtensionFactory. If extension scanning is enabled (the default), it would load fine without the --extensions flag.
```
So I left only ```--extensions "com.wiremock.gui.WireMockGuiExtension"``` and run docker compose again and wiremock server starts with following extensions:
```
 ✔ Container wiremock Healthy                                                                                                        2.2s
...
version:                      3.13.2
port:                         8080
...
extensions:                   wiremock-gui,jwt-signing-key-settings-listener,jwt-initialiser,jwt-template-helpers,response-template,webhook
```
inside of wiremock's container

```
root@000ec83d57eb:/home/wiremock# ls -l /var/wiremock/extensions/
total 26900
-rw-rw-r--. 1 1001 984  3104245 Jun  2 07:00 wiremock-gui-1.1.0.jar
-rw-rw-r--. 1 1001 984 24433239 Aug 19 12:05 wiremock-jwt-extension-standalone-0.3.0.jar
-rw-rw-r--. 1 1001 984      283 Aug 19 12:05 wiremock-jwt-extension-standalone-0.3.0.jar:Zone.Identifier
```
